package com.example.cbcnewsapp

data class MainVisual(
    val active: Boolean,
    val altText: String,
    val createdAt: Long,
    val credit: String,
    val derivatives: Derivatives,
    val description: String,
    val draft: Boolean,
    val embedTypes: Any,
    val height: Int,
    val id: Int,
    val language: String,
    val modifiedAt: Long,
    val publishedAt: Long,
    val readableCreatedAt: String,
    val readableModifiedAt: String,
    val readablePublishedAt: String,
    val readableUpdatedAt: String,
    val source: String,
    val sourceId: String,
    val title: String,
    val type: String,
    val typeAttributes: TypeAttributesXX,
    val updatedAt: Long,
    val url: String,
    val useOriginalImage: Boolean,
    val version: String,
    val width: Int
)